#### Enrico Julian U. Absin
#### CS 3101N
### Linear Transformations
# <font color = black> Code Challenges</font>
1. Develop a python function from scratch that will find the determinants of any $n \times n$ matrix.

2. Develop a python function from scratch that will find both the eigenvectors and eigenvalues of any $n \times n$ matrix.

3. Test your functions from a randomly generated $n \times n$ matrix.

In [2]:
import numpy as np

def calculate_determinant(A):

    if not np.array_equal(A.shape, A.T.shape):
        raise ValueError("Input matrix must be square.")

    if len(A.shape) == 1 and A.shape[0] == 1:
        return A[0, 0]

    determinant_value = 0
    for i in range(A.shape[0]):
        minor = np.delete(A, i, axis=0)
        minor = np.delete(minor, i, axis=1)
        determinant_value += (-1) ** i * A[i, 0] * calculate_determinant(minor)

    return determinant_value

def generate_random_matrix(n):
    return np.random.rand(n, n)

A = generate_random_matrix(3)

# Print the random matrix.
print("Random Matrix:")
print(A)

det_A = calculate_determinant(A)
print("Determinant:", det_A)

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Random Matrix:
[[0.57036722 0.78837386 0.34682104]
 [0.86982973 0.79707292 0.45612074]
 [0.27580394 0.30090315 0.6919858 ]]
Determinant: 0.0
Eigenvalues:
[ 1.74146585 -0.1521014   0.47006149]

Eigenvectors:
[[-5.91965384e-01 -7.37263279e-01 -3.31212702e-01]
 [-7.20078669e-01  6.75605546e-01 -3.44323075e-01]
 [-3.62027202e-01  5.71934230e-05  8.78487203e-01]]
