#### Enrico Julian U. Absin
#### CS 3101N
### Linear Transformations
# <font color = black> Code Challenges</font>
1. Develop a python function from scratch that will find the determinants of any $n \times n$ matrix.

2. Develop a python function from scratch that will find both the eigenvectors and eigenvalues of any $n \times n$ matrix.

3. Test your functions from a randomly generated $n \times n$ matrix.

In [1]:
import numpy as np

def calculate_determinant(A):

    if not np.array_equal(A.shape, A.T.shape):
        raise ValueError("Input matrix must be square.")

    if len(A.shape) == 1 and A.shape[0] == 1:
        return A[0, 0]

    determinant_value = 0
    for i in range(A.shape[0]):
        minor = np.delete(A, i, axis=0)
        minor = np.delete(minor, i, axis=1)
        determinant_value += (-1) ** i * A[i, 0] * calculate_determinant(minor)

    return determinant_value

def generate_random_matrix(n):
    return np.random.rand(n, n)

A = generate_random_matrix(3)

# Print the random matrix.
print("Random Matrix:")
print(A)

det_A = calculate_determinant(A)
print("Determinant:", det_A)

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Random Matrix:
[[0.27079999 0.08285691 0.23962683]
 [0.34541467 0.21991277 0.77343492]
 [0.08523227 0.72250361 0.31319833]]
Determinant: 0.0
Eigenvalues:
[ 1.09652922  0.16215918 -0.45477731]

Eigenvectors:
[[-0.2639257  -0.91347588 -0.14534006]
 [-0.69452551  0.02283409 -0.71250591]
 [-0.66931124  0.40625166  0.68644853]]
