#### Enrico Julian U. Absin
#### CS 3101N
### Linear Transformations
# <font color = black> Code Challenges</font>
1. Develop a python function from scratch that will find the determinants of any $n \times n$ matrix.

2. Develop a python function from scratch that will find both the eigenvectors and eigenvalues of any $n \times n$ matrix.

3. Test your functions from a randomly generated $n \times n$ matrix.

In [9]:
import numpy as np

def calculate_determinant(A):

    if not np.array_equal(A.shape, A.T.shape):
        raise ValueError("Input matrix must be square.")

    if len(A.shape) == 1 and A.shape[0] == 1:
        return A[0, 0]

    determinant_value = 0
    for i in range(A.shape[0]):
        minor = np.delete(A, i, axis=0)
        minor = np.delete(minor, i, axis=1)
        determinant_value += (-1) ** i * A[i, 0] * calculate_determinant(minor)

    return determinant_value

def generate_random_matrix(n):
    return np.random.rand(n, n)

A = generate_random_matrix(3)

# Print the random matrix.
print("Random Matrix:")
print(A)

det_A = calculate_determinant(A)
print("Determinant:", det_A)

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Random Matrix:
[[0.31966502 0.33746512 0.77827126]
 [0.70634087 0.28191668 0.99698704]
 [0.66336534 0.6432845  0.10082153]]
Determinant: 0.0
Eigenvalues:
[ 1.57698936 -0.19806345 -0.67652269]

Eigenvectors:
[[-0.50844738 -0.72693347 -0.43710398]
 [-0.6820041   0.65738396 -0.47338078]
 [-0.52569161  0.19852974  0.76475535]]
