#### Enrico Julian U. Absin
#### CS 3101N
### Matrix Algebra
# <font color = black> Code Challenges</font>
1. Without the use of any python libraries or modules, develop a function that can perform matrix addition, given two numpy matrices.

2. Without the use of any python libraries or modules, develop a function that can multiply two numpy matrices.

3. The rule of distributivity states that given two matrices 𝐴 and 𝐵 and a scalar, 𝑘, then 𝑘(𝐴+𝐵)=𝑘𝐴+𝑘𝐵. Instead of writing a proof mathematically, develop two codes for 𝑘(𝐴+𝐵) and 𝑘𝐴+𝑘𝐵.

4. Without using a python library or modules develop a function that can extract the diagonal of a numpy matrix.

5. Without using a python library or modules develop a function that can find a trace of a numpy matrix.

In [7]:
import numpy as np

In [15]:
#1.#
def matrix_addition(A, B):
  if not np.array_equal(A.shape, B.shape):
    raise ValueError("Input matrices should have the same shape.")

  C = np.zeros_like(A)
  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      C[i, j] = A[i, j] + B[i, j]

  return C

A = np.array([[1, 3, 8], [3, 7, 2]])
B = np.array([[7, 6, 5], [15, 14, 12]])

C = matrix_addition(A, B)

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("Sum of A and B:")
print(C)

Matrix A:
[[1 3 8]
 [3 7 2]]
Matrix B:
[[ 7  6  5]
 [15 14 12]]
Sum of A and B:
[[ 8  9 13]
 [18 21 14]]


In [9]:
#2.#
def matrix_multiplication(A, B):
  if A.shape[1] != B.shape[0]:
    raise ValueError("Incompatible matrix dimensions for multiplication.")

  m, n, p = A.shape[0], A.shape[1], B.shape[1]
  C = np.zeros((m, p))

  for i in range(m):
    for j in range(p):
      for k in range(n):
        C[i, j] += A[i, k] * B[k, j]

  return C

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = matrix_multiplication(A, B)

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("Product of A and B:")
print(C)

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Product of A and B:
[[19. 22.]
 [43. 50.]]


In [12]:
#4.#
def distribute_k(k, A, B):
  if not np.array_equal(A.shape, B.shape):
    raise ValueError("Input matrices must have the same shape.")

  sum_matrix = A + B
  return k * sum_matrix

def distribute_k_separate(k, A, B):
  if not np.array_equal(A.shape, B.shape):
    raise ValueError("Input matrices must have the same shape.")

  kA = k * A
  kB = k * B
  return kA + kB

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

k = 2

C = distribute_k(k, A, B)

D = distribute_k_separate(k, A, B)

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("k*(A+B):")
print(C)
print("kA+kB:")
print(D)

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
k*(A+B):
[[12 16]
 [20 24]]
kA+kB:
[[12 16]
 [20 24]]


In [14]:
def matrix_trace(A):
  if not np.array_equal(A.shape, A.T.shape):
    raise ValueError("Input matrix must be square.")

  trace = 0
  for i in range(A.shape[0]):
    trace += A[i, i]

  return trace

A = np.array([[1, 3, 6], [2, 4, 6], [3, 6, 9]])

trace = matrix_trace(A)

print("Matrix A:")
print(A)
print("Trace of A:", trace)

Matrix A:
[[1 3 6]
 [2 4 6]
 [3 6 9]]
Trace of A: 14
