#### Enrico Julian U. Absin
#### CS 3101N
### Matrix Algebra
## <font color = red> Code Challenges</font>
1. Without the use of any python libraries or modules, develop a function that can perform matrix addition, given two numpy matrices.

2. Without the use of any python libraries or modules, develop a function that can multiply two numpy matrices.

3. The rule of distributivity states that given two matrices 𝐴 and 𝐵 and a scalar, 𝑘, then 𝑘(𝐴+𝐵)=𝑘𝐴+𝑘𝐵. Instead of writing a proof mathematically, develop two codes for 𝑘(𝐴+𝐵) and 𝑘𝐴+𝑘𝐵.

4. Without using a python library or modules develop a function that can extract the diagonal of a numpy matrix.

5. Without using a python library or modules develop a function that can find a trace of a numpy matrix.

In [1]:
import numpy as np

In [15]:
#1.#
def matrix_addition(A, B):
  if not np.array_equal(A.shape, B.shape):
    raise ValueError("Input matrices should have the same shape.")

  C = np.zeros_like(A)
  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      C[i, j] = A[i, j] + B[i, j]

  return C

A = np.array([[1, 3, 8], [3, 7, 2]])
B = np.array([[7, 6, 5], [15, 14, 12]])

C = matrix_addition(A, B)

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("Sum of A and B:")
print(C)

Matrix A:
[[1 3 8]
 [3 7 2]]
Matrix B:
[[ 7  6  5]
 [15 14 12]]
Sum of A and B:
[[ 8  9 13]
 [18 21 14]]


In [9]:
#2.#
def matrix_multiplication(A, B):
  if A.shape[1] != B.shape[0]:
    raise ValueError("Incompatible matrix dimensions for multiplication.")

  m, n, p = A.shape[0], A.shape[1], B.shape[1]
  C = np.zeros((m, p))

  for i in range(m):
    for j in range(p):
      for k in range(n):
        C[i, j] += A[i, k] * B[k, j]

  return C

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = matrix_multiplication(A, B)

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("Product of A and B:")
print(C)

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Product of A and B:
[[19. 22.]
 [43. 50.]]


In [12]:
#4.#
def distribute_k(k, A, B):
  if not np.array_equal(A.shape, B.shape):
    raise ValueError("Input matrices must have the same shape.")

  sum_matrix = A + B
  return k * sum_matrix

def distribute_k_separate(k, A, B):
  if not np.array_equal(A.shape, B.shape):
    raise ValueError("Input matrices must have the same shape.")

  kA = k * A
  kB = k * B
  return kA + kB

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

k = 2

C = distribute_k(k, A, B)

D = distribute_k_separate(k, A, B)

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("k*(A+B):")
print(C)
print("kA+kB:")
print(D)

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
k*(A+B):
[[12 16]
 [20 24]]
kA+kB:
[[12 16]
 [20 24]]


In [14]:
#5.#
def matrix_trace(A):
  if not np.array_equal(A.shape, A.T.shape):
    raise ValueError("Input matrix must be square.")

  trace = 0
  for i in range(A.shape[0]):
    trace += A[i, i]

  return trace

A = np.array([[1, 3, 6], [2, 4, 6], [3, 6, 9]])

trace = matrix_trace(A)

print("Matrix A:")
print(A)
print("Trace of A:", trace)

Matrix A:
[[1 3 6]
 [2 4 6]
 [3 6 9]]
Trace of A: 14


---
## <font color = red> Problem Solving</font>
---
1. Solve $X$ given that:
\begin{equation}
A =
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
\end{bmatrix},
B =
\begin{bmatrix}
-1 & 0 \\
1 & 1 \\
\end{bmatrix}
\end{equation}
- $3X = A-2B$ <br>
**Manual Solution:**
    - 2B
    $
     \begin{equation}
     2
        \begin{bmatrix}
            -1 & 0\\
            1 & 1\\
        \end{bmatrix}
        \xrightarrow[]{}
        \begin{bmatrix}
            -2 & 0\\
            2 & 2\\
        \end{bmatrix}
    \end{equation}
    $ 
    - A - B
    \begin{equation}
        \begin{bmatrix}
            1 & 2\\
            3 & 4\\
        \end{bmatrix}
        \begin{bmatrix}
            -2 & 0\\
            2 & 2\\
        \end{bmatrix}
        \xrightarrow[]{}
        \begin{bmatrix}
            3 & 2\\
            1 & 2\\
        \end{bmatrix}
    \end{equation}
    - Isolate $X$ by dividing by 3
    \begin{equation}
        \frac{1}{3}
        \begin{bmatrix}
            3 & 2\\
            1 & 2\\
        \end{bmatrix}
        \xrightarrow[]{}     
        \begin{bmatrix}
            1 & \frac{2}{3}\\
            \frac{1}{3} & \frac{2}{3}\\
        \end{bmatrix}
    \end{equation}

    **Pythonic Solution:**

In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[-1, 0], [1, 1]])

X = (A - 2 * B) / 3 #Calculates the equation

print("X:")
print(X)

X:
[[1.         0.66666667]
 [0.33333333 0.66666667]]


- $2(A-B+2X) = 3(X-B)$ <br>
**Manual Solution:**
    - Distribute the values:
    <br>
    \begin{equation}
    2A - 2B + 4X = 3X - 3B
    \end{equation}
    - Combine the similar terms:
    <br>
    \begin{equation}
    2A + B = X
    \end{equation}
    - Substitution:
     \begin{equation}
        X
        \xrightarrow[]{}
        -B - 2A
        \xrightarrow[]{}
          -
        \begin{bmatrix}
            -1 & 0\\
            1 & 1\\
        \end{bmatrix}
          -2
        \begin{bmatrix}
            1 & 2\\
            3 & 4\\
        \end{bmatrix}
    \end{equation}
    - Multiplication and addition of matrix:
     \begin{equation}
        X
        \xrightarrow[]{}
          -
        \begin{bmatrix}
            -1 & 0\\
            1 & 1\\
        \end{bmatrix}
          -    
        \begin{bmatrix}
            2 & 4\\
            6 & 8\\
        \end{bmatrix}
        \xrightarrow[]{}
        \begin{bmatrix}
            -1 & -4\\
            -7 & -9\\
        \end{bmatrix}
    \end{equation}

  **Pythonic Solution:**

In [5]:
X = -B - 2 * A #Calculates the equation

print("X:")
print(X)

X:
[[-1 -4]
 [-7 -9]]


2. Write $B$ as a linear combination of the other matrices, if possible.
\begin{equation}
A_1 =
\begin{bmatrix}
1 & 2 \\
-1 & 1 \\
\end{bmatrix},
A_2 =
\begin{bmatrix}
0 & 1 \\
2 & 1 \\
\end{bmatrix},
B =
\begin{bmatrix}
2 & 5 \\
0 & 3 \\
\end{bmatrix}
\end{equation}
<br><br>
$B = x_1 * A_1 + x_2 * A_2$

<br><br>
$
    \begin{equation}
        x_1
        \begin{bmatrix}
            1 & 2\\
            -1 & 1\\
        \end{bmatrix}
        + 
        \begin{bmatrix}
            0 & 1\\
            2 & 1\\
        \end{bmatrix}
        =
        \begin{bmatrix}
            2 & 5\\
            0 & 3\\
        \end{bmatrix}
    \end{equation}
$
    $x_1 + 0x_2 = 2$<br>
    $2x_1 + x_2 = 5$<br>
    $-x_1 + 2x_2 = 0$<br>
    $x_1 + x_2 = 3$<br><br>
This gives us the values of $x_1$ and $x_2$:<br>
    $x_1 = 2$<br>
    $x_2 = 1$<br>
<br>which gives the combination:<br>
$B = 2 * A_1 + A_2$


$
\begin{equation}
A_1 =
\begin{bmatrix}
1 & 0 \\
0 & 1 \\
\end{bmatrix},
A_2 =
\begin{bmatrix}
0 & 1 \\
1 & 0 \\
\end{bmatrix},
A_3 =
\begin{bmatrix}
1 & -1 \\
1 & 1 \\
\end{bmatrix},
B =
\begin{bmatrix}
2 & 5 \\
0 & 3 \\
\end{bmatrix}
\end{equation}
$
<br>
<br>
$B = c_1 * A_1 + c_2 * A_2 + c_3 * A_3$
<br><br>
$c_1 * A_1 + c_2 * A_2 + c_3 * A_3 = B$ 
<br><br>
Substitute:
$
    \begin{equation}
        c_1 *
        \begin{bmatrix}
            1 & 0\\
            0 & 1\\
        \end{bmatrix}
        +
        c_2 *
        \begin{bmatrix}
            0 & 1\\
            1 & 0\\
        \end{bmatrix}
        +
        c_3 *
        \begin{bmatrix}
            1 & -1\\
            1 & 1\\
        \end{bmatrix}
        =
        \begin{bmatrix}
            2 & 5\\
            0 & 3\\
        \end{bmatrix}
    \end{equation}
$
<br><br>
$c_1 + c_3 = 2$<br>
$c_2 - c_3 = 5$<br>
$c_2 + c_3 = 0$<br>
$c_1 + c_3 = 3$
<br><br>
The equation $c_2 + c_3 = 0$, which is inconsistent with the other equations, yields no solutions and thus $B$ cannot be expressed as a linear combination of $A_1$, $A_2$, and $A_3$.

3. Given the following:
\begin{equation}
A =
\begin{bmatrix}
1 & 2 \\
2 & 6 \\
\end{bmatrix},
b_1 =
\begin{bmatrix}
3 \\
5 \\
\end{bmatrix},
b_2 =
\begin{bmatrix}
-1 \\
2 \\
\end{bmatrix},
b_3 =
\begin{bmatrix}
2 \\
0 \\
\end{bmatrix}
\end{equation}
- Find $A^{-1}$, and use this to solve for $Ax=b_1,Ax=b_2,Ax=b_3$
- Solve all three linear systems by row reducing the augmented matrix:
\begin{equation}
\begin{bmatrix}
\begin{array}{c|ccc}
A &
b_1 &
b_2 &
b_3 \\
\end{array}
\end{bmatrix}
\end{equation}

$ A^{-1} = (\frac{1}{det(A)}) * 
\begin{bmatrix}
d & -b \\
-c & a \\
\end{bmatrix} \\  $

$ det(A) = (1 * 6) - (2 * 2) = 6 - 4 = 2 $ 

$ A^{-1} = (\frac{1}{2}) * 
\begin{bmatrix}
6 & -2 \\
-2 & 1 \\
\end{bmatrix} = 
\begin{bmatrix}
3 & -1 \\
-1 & \frac{1}{2} \\
\end{bmatrix} \\ 
$

$ A | b_1 = \begin{bmatrix}\begin{array}{cc|c}
1 & 2 & 3 \\
2 & 6 & 5 \\
\end{array}\end{bmatrix}
\xrightarrow{\text{R}_{2}-2\text{R}_{1}} 
\begin{bmatrix}\begin{array}{cc|c}
1 & 2 & 3 \\
0 & 2 & -1 \\
\end{array}\end{bmatrix}
\xrightarrow{\frac{1}{2}R_2}
\begin{bmatrix}\begin{array}{cc|c}
1 & 2 & 3 \\
0 & 1 & -0.5 \\
\end{array}\end{bmatrix}
\xrightarrow{\text{R}_{1}-2\text{R}_{2}} 
\begin{bmatrix}\begin{array}{cc|c}
1 & 0 & 4 \\
0 & 1 & -0.5 \\
\end{array}\end{bmatrix} \\
{A | b_1: x_1 = 4, x_2 = -0.5} \\
$

$ A | b_2 = \begin{bmatrix}\begin{array}{cc|c}
1 & 2 & -1 \\
2 & 6 & 2 \\
\end{array}\end{bmatrix}
\xrightarrow{\text{R}_{2}-2\text{R}_{1}} 
\begin{bmatrix}\begin{array}{cc|c}
1 & 2 & -1 \\
0 & 2 & 4 \\
\end{array}\end{bmatrix}
\xrightarrow{\frac{1}{2}R_2}
\begin{bmatrix}\begin{array}{cc|c}
1 & 2 & -1 \\
0 & 1 & 2 \\
\end{array}\end{bmatrix}
\xrightarrow{\text{R}_{1}-2\text{R}_{2}} 
\begin{bmatrix}\begin{array}{cc|c}
1 & 0 & -5 \\
0 & 1 & 2 \\
\end{array}\end{bmatrix} \\
{A | b_2: x_1 = -5, x_2 = 2} \\ $

$ A | b_3 = \begin{bmatrix}\begin{array}{cc|c}
1 & 2 & 2 \\
2 & 6 & 0 \\
\end{array}\end{bmatrix}
\xrightarrow{\text{R}_{2}-2\text{R}_{1}} 
\begin{bmatrix}\begin{array}{cc|c}
1 & 2 & 2 \\
0 & 2 & -4 \\
\end{array}\end{bmatrix}
\xrightarrow{\frac{1}{2}R_2}
\begin{bmatrix}\begin{array}{cc|c}
1 & 2 & 2 \\
0 & 1 & -2 \\
\end{array}\end{bmatrix}
\xrightarrow{\text{R}_{1}-2\text{R}_{2}} 
\begin{bmatrix}\begin{array}{cc|c}
1 & 0 & 6 \\
0 & 1 & -2 \\
\end{array}\end{bmatrix} \\
\underline{A | b_3: x_1 = 6, x_2 = -2} \\
$

4. In each given, determine if $b$ in in $col(A)$, and $w$ is in $row(A)$
\begin{equation}
A =
\begin{bmatrix}
1 & 0 & -1 \\
1 & 1 & 1 \\
\end{bmatrix},
b =
\begin{bmatrix}
3 \\
2 \\
\end{bmatrix},
w =
\begin{bmatrix}
-1 &
1 &
1
\end{bmatrix},
\end{equation}
**Perform row operations to echelon form:**
$$
\begin{bmatrix}\begin{array}{ccc|c}
1 & 0 & -1 & 3\\
1 & 1 & 1 & 2\\
\end{array}\end{bmatrix}
\xrightarrow{\text{R}_{2}-\text{R}_{1}} 
\begin{bmatrix}\begin{array}{ccc|c}
1 & 0 & -1 & 3\\
0 & 1 & 2 & -1\\
\end{array}\end{bmatrix}
$$
$$
\begin{bmatrix}\begin{array}{ccc}
1 & 0 & -1\\
1 & 1 & 2\\
\end{array}\end{bmatrix}
$$
<br />

$b$ is in $col(A)$ because it is consistent and has a unique solution, while $w$ is in $row(A)$ because it satisfies the equation
$ 
w = y_1
\begin{bmatrix}
-1 & 0 & -1
\end{bmatrix} + y_2
\begin{bmatrix}
1 & 1 & 1
\end{bmatrix}
$ 
.

\begin{equation}
A =
\begin{bmatrix}
1 & 1 & -1 \\
1 & 3 & 0 \\
3 & -1 & -5 \\
\end{bmatrix},
b =
\begin{bmatrix}
1 \\
2 \\
1 \\
\end{bmatrix},
w =
\begin{bmatrix}
1 &
-3 &
-3
\end{bmatrix},
\end{equation}
**Perform row operations to echelon form:**
$$
\begin{bmatrix}\begin{array}{ccc|c}
1 & 1 & -1 & 1\\
1 & 3 & 0 & 2\\
3 & -1 & -5 & 1\\
\end{array}\end{bmatrix}
\xrightarrow{\text{R}_{2}-\text{R}_{1},\text{R}_{3}-\text{R}_{1}} 
\begin{bmatrix}\begin{array}{ccc|c}
1 & 1 & -1 & 1\\
0 & 2 & 1 & 1\\
0 & -4 & -2 & -2\\
\end{array}\end{bmatrix}
$$

$$
\begin{bmatrix}\begin{array}{ccc|c}
1 & 1 & -1 & 1\\
0 & 2 & 1 & 1\\
0 & -4 & -2 & -2\\
\end{array}\end{bmatrix}
\xrightarrow{\text{R}_{2}/\text{2}} 
\begin{bmatrix}\begin{array}{ccc|c}
1 & 1 & -1 & 1\\
0 & 1 & \frac{1}{2} & \frac{1}{2}\\
0 & -4 & -2 & -2\\
\end{array}\end{bmatrix}
$$

$$
\begin{bmatrix}\begin{array}{ccc|c}
1 & 1 & -1 & 1\\
0 & 1 & \frac{1}{2} & \frac{1}{2}\\
0 & -4 & -2 & -2\\
\end{array}\end{bmatrix}
\xrightarrow{\text{R}_{3}+\text{4}(\text{R}_{2})} 
\begin{bmatrix}\begin{array}{ccc|c}
1 & 1 & -1 & 1\\
0 & 1 & \frac{1}{2} & \frac{1}{2}\\
0 & 0 & 0 & 0\\
\end{array}\end{bmatrix}
$$

$$
\begin{bmatrix}\begin{array}{ccc|c}
1 & 1 & -1\\
0 & 1 & \frac{1}{2}\\
0 & 0 & 0\\
\end{array}\end{bmatrix}
$$

Therefore, $b$ is in $col(A)$ and $w$ is in $row(A)$.


5. Find the rank and nullity of:
$
\begin{bmatrix}
2 & 4 & 0 & 0 & 1 \\
6 & 3 & 5 & 1 & 0 \\
1 & 0 & 2 & 2 & 5 \\
1 & 1 & 1 & 1 & 1 \\
\end{bmatrix}
$

$
 \begin{equation}
    \begin{bmatrix}
        2 & 4 & 0 & 0 & 1 \\
        6 & 3 & 5 & 1 & 0 \\
        1 & 0 & 2 & 2 & 5 \\
        1 & 1 & 1 & 1 & 1 \\
    \end{bmatrix}
    \xrightarrow[]{R_2 - 3R_1}
    \begin{bmatrix}
        2 & 4 & 0 & 0 & 1 \\
        0 & -9 & 5 & 1 & -3 \\
        1 & 0 & 2 & 2 & 5 \\
        1 & 1 & 1 & 1 & 1 \\
    \end{bmatrix}
    \xrightarrow[]{R_3 - \frac{1}{2}R_1}
    \begin{bmatrix}
        2 & 4 & 0 & 0 & 1 \\
        0 & -9 & 5 & 1 & -3 \\
        0 & 2 & 2 & 2 & 4.5 \\
        1 & 1 & 1 & 1 & 1 \\
    \end{bmatrix}
    \xrightarrow[]{R_1 - 2}
    \begin{bmatrix}
        0 & 2 & -2 & -2 & -3 \\
        0 & -9 & 5 & 1 & -3 \\
        0 & 2 & 2 & 2 & 4.5 \\
        1 & 1 & 1 & 1 & 1 \\
    \end{bmatrix}
    \xrightarrow[]{R_3 - R_1}
    \begin{bmatrix}
        0 & 2 & -2 & -2 & -3 \\
        0 & -9 & 5 & 1 & -3 \\
        0 & 0 & 4 & 4 & 7.5 \\
        1 & 1 & 1 & 1 & 1 \\
    \end{bmatrix}
    \xrightarrow[]{R_1(R_4)}
    \begin{bmatrix}
        1 & 2 & -2 & -2 & -3 \\
        0 & -9 & 5 & 1 & -3 \\
        0 & 0 & 4 & 4 & 7.5 \\
        1 & 1 & 1 & 1 & 1 \\
    \end{bmatrix}
    \xrightarrow[]{R_4 - 1}
    \begin{bmatrix}
        1 & 2 & -2 & -2 & -3 \\
        0 & -9 & 5 & 1 & -3 \\
        0 & 0 & 4 & 4 & 7.5 \\
        0 & 0 & 0 & 0 & 0 \\
    \end{bmatrix}
\end{equation}
$


Therefore, the rank of the matrix is 4 while its nullity is 1.