#### Enrico Julian U. Absin
#### CS 3101N
### System of Linear Equations
# <font color = red> ASSIGNMENT 1</font>
- The above python functions are developed to automate forward elimination.
- To complete the process of determining the solution, create a function or steps of function that will automate backward substitution.
#### For forward elimination:

In [3]:
import numpy as np

In [5]:
# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# ========================================================================a=====
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate ab
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

#### For backward substitution:

In [7]:
def BackwardSubstitution(U, b):
    n = U.shape[0]
    x = [b[i] for i in range(n-1, -1, -1)]
    for i in range(n-1, -1, -1):
        x[i] -= sum(U[i, j] * x[j] for j in range(i+1, n))
        if U[i, i] != 0:
            x[i] /= U[i, i]
        else:
            x[i] = 0
    return x


# <font color = red> ASSIGNMENT 2</font>
---
1. Provide reasons why each of the following equations is, or is not, a linear equation.
- $\cos{\theta}x+4y+z = \sqrt{3}$
<br>It is **not a linear equation**. This is because the variable x is in the cosine function. The cosine function is a non-linear function, which means that the equation is not linear.<br>
- $cos{x}4y+z = \sqrt{3}$
<br>Similar to the first equation, it is **not a linear equation** for the same reason. The cosine function is a non-linear function, which means that the equation is not linear.<br>
- $x^{-1}+7y+z = \sin{(\frac{\pi}{2})}$
<br>It is **not a linear equation** since the variable x is in the inverse function and the variable z is in the sine function. Both of these functions are non-linear functions, which means that the equation is not linear.<br>
- $x^1+y^1+z^1=0$
<br>It is a **linear equation** due to the variables x and y having a degree of 1 and the coefficients 1, 2, and 3 being constants. Therefore, the equation is linear.
---
2. Find the solutions to the linear equations: <br>

A) $2x_1+3x_2 =5$ <br>

B) $4x_1+3x_2+2x_3 = 1$ <br>

C) $3x - 6y = 0$ <br>
#### Manual Solutions: <br>
A) 
$
2x_1+3x_2 =5 \\
\frac{2x_1}{2} = \frac{5 - 3x_2}{2} 
\boxed{x_1 = \frac{5}{2} - \frac{3}{2}x_2}
$ Final Answer

B)
$
4x_1+3x_2+2x_3 = 1 \\
\frac{4x_1}{4} = \frac{1 - 3x_2 - 2x_3}{4} 
\boxed{x_1 = \frac{1}{4} - \frac{3}{4}x_2 - \frac{1}{2}x_3}
$ Final Answer

C)
$
3x - 6y = 0 \\
\frac{3x}{3} = \frac{6y}{3} 
\boxed{x = 2y} 
$ Final Answer 
---


---
3. Solve the following systems of linear equations: <br>

a) $ L_1: x - y = 0 \\
L_2: 2x + y = 3
$

b) $ L_1: x + 5y = -1 \\
L_2: -x + y = -5 \\
L_3: 2x + 4y = 4
$

c) $ L_1: 2x_1 + 3x_2 -x_3 = -1 \\
L_2: x_1 + x_3 = 0 \\
L_3: -x_1 + 2x_2 - 2x_3 = 0
$

#### Manual solution:

a) 
Forward elimination:$ \\
-2(x - y = 0) \\
-2x + 2y = 0 \space + \space2x + y = 3
\\ = \frac{3y}{3} = \frac{3}{3} \\
\boxed{y = 1} \\
$


Backward substitution: 
$
x - (1) = 0 \\
\boxed{x = 1}
$ 

<br><br>

b) <br> $
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    -1 & 1 &\bigm| & -5 \\
    2 & 4 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6 &\bigm| & -6 \\
    2 & 4 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6 &\bigm| & -6 \\
    0 & -6 &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow{\frac{1}{6}\text{R}_{2}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    0 & -6 &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 5\text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & 4 \\
    0 & 1 &\bigm| & -1 \\
    0 & -6 &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + 6\text{R}_{2}}
\begin{pmatrix}
    1 & 0 &\bigm| & 4 \\
    0 & 1 &\bigm| & -1 \\
    0 & 0 &\bigm| & 0 \\
\end{pmatrix}
$ <br>
Backward Substitution:<br>
$x = 4 + 0t$<br>
$y = -1 + 0t$ <br>
x = 4 <br> y = -1

<br><br>

c) <br> $
\begin{pmatrix}
    2 & 3 & -1 &\bigm| & -1 \\
    1 & 0 & 1 &\bigm| & 0 \\
    -1 & 2 & -2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\frac{1}{2}\text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    1 & 0 & 1 &\bigm| & 0 \\
    -1 & 2 & -2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    0 & \frac{-3}{2} & \frac{3}{2} &\bigm| & \frac{1}{2} \\
    -1 & 2 & -2 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{1}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    0 & \frac{-3}{2} & \frac{3}{2} &\bigm| & \frac{1}{2} \\
    0 & \frac{7}{2} & \frac{-5}{2} &\bigm| & \frac{-1}{2} \\
\end{pmatrix}
\xrightarrow{\frac{-2}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    0 & 1 & -1 &\bigm| & \frac{-1}{3} \\
    0 & \frac{7}{2} & \frac{-5}{2} &\bigm| & \frac{-1}{2} \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - \frac{7}{2}\text{R}_{2}}
\begin{pmatrix}
    1 & \frac{3}{2} & \frac{-1}{2} &\bigm| & \frac{-1}{2} \\
    0 & 1 & -1 &\bigm| & \frac{-1}{3} \\
    0 & 0 & 1 &\bigm| & \frac{-5}{9} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \frac{3}{2}\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & \frac{1}{3} &\bigm| & \frac{1}{3} \\
    0 & 1 & -1 &\bigm| & \frac{-1}{3} \\
    0 & 0 & 1 &\bigm| & \frac{-5}{9} \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - \frac{1}{3}\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 0 &\bigm| & 0 \\
    0 & 1 & -1 &\bigm| & \frac{-1}{3} \\
    0 & 0 & 1 &\bigm| & \frac{-5}{9} \\
\end{pmatrix}
$

Backward Substitution:<br>
$\boxed{x_1 = 0}$<br>
$\boxed{x_3 = -\frac{5}{9}}$ <br>
$x_2 - x_3 = -\frac{1}{3}$<br>
$x_2 - (-\frac{5}{9}) = -\frac{1}{3}$<br>
$x_2 = -\frac{1}{3} - \frac{5}{9}$<br>
$\boxed{x_2 = -\frac{8}{9}}$


---
4. Provide reasons why the given matrices are either a row echelon, a reduced row echelon, or niether both. <br> <br>
a. It is **neither** row echelon form or reduced row echelon form. The leading entry of Row 2 appears in a column to the left of the leading entry of Row 1, and is not equal to 1. This directly contradicts the definition of both row echelon form and reduced row echelon form.<br>
b. It is in **row echelon form** but not **reduced row echelon form**. Since the leading entry in a row is situated in a column to the left of the leading entry in the row above it but the leading entry in Row 1 is not equal to 1.<br>
c. This matrix is in **reduced row echelon form** since the bottom row contains the maximum number of zeros and each row boasts a leading entry of 1.<br>
d. This is in **reduced row echelon form**, since it fulfills all criteria; zero rows at bottom, leading 1s to the left, and no non-zero entries outside leading positions.<br>
e. This is **not in either form** due to leading 1s but lacks zero rows at the bottom. Can't be reduced row echelon if not row echelon.<br>
f. This matrix is in **row echelon form** since there are non-zero rows above zero rows, leading entries right-shifted, and leading entries all 1.<br>
g. It is in **neither form** since the leading entry in Row 2 not left of Row 1's.<br>
h. It is in **row echelon form only**, not reduced. This is due to zero rows at the bottom, each leading entry right-shifted.<br>
---
5. Solve the following systems of linear equations.<br>
a.
\begin{equation}
x_1+2x_2-3x_3=9 \\
2x_1-x_2-x_3=0 \\
4x_1-x_2+x_3=4 \\
\end{equation}
<br>
<br>

Manual Solution:<br><br>
$
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    2 & -1 & -1 &\bigm| & 0 \\
    4 & -1 & 1 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & -5 & 5 &\bigm| & -18 \\
    4 & -1 & 1 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 4\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & -5 & 5 &\bigm| & -18 \\
    0 & -9 & 13 &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{-\frac{1}{5}\text{R}_{2}}
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & 1 & -1 &\bigm| & \frac{18}{5} \\
    0 & -9 & 13 &\bigm| & -32 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 9\text{R}_{2}}
\begin{pmatrix}
    1 & 2 & -3 &\bigm| & 9 \\
    0 & 1 & -1 &\bigm| & \frac{18}{5} \\
    0 & 0 & 4 &\bigm| & -\frac{2}{5} \\
\end{pmatrix} \\
\\$
New Equations:$\\
= x_1 + 2x_2 - 3x_3 = 9\\
= x_2 - (-x_3) = \frac{18}{5}\\
= 4x_3 = -\frac{2}{5}\\$

Backwards Substitution:
$\\
\frac{4x_3}{4} = \frac{\frac{2}{5}}{4}\\
\boxed{x_3 = \frac{1}{10}}\\
\\
x_2 - (-x_3) = \frac{18}{5}\\
x_2 - (\frac{1}{10}) = \frac{18}{5}\\
x_2 = \frac{18}{5} + \frac{1}{10}\\
\boxed{x_2 = \frac{37}{10}}\\
x_1 + 2x_2 - 3x_3 = 9\\
x_1 + 2(\frac{37}{10}) - 3(\frac{1}{10}) = 9\\
x_1 + \frac{37}{5}) - \frac{3}{10} = 9\\
\boxed{x_1 = \frac{19}{10}}\\
$

In [27]:
#Pythonic Solution#
import numpy as np
A = np.array([[1, 2, -3, 9],
              [2, -1, -1, 0],
              [4, -1, 1, 4]])

print("A")
print(A,'\n')
A = RowAdd(A, 0, 1, -2)
print("A1")
print(A,'\n')
A = RowAdd(A, 0, 2, -4)
print("A2")
print(A,'\n')
A = RowScale(A, 1, -1/5)
print("A3")
print(A,'\n')
A = RowAdd(A, 1, 2, 9)
print("A4")
print(A,'\n')

last_entries = []
for row in A:
    last_entry = row[-1]
    last_entries.append(last_entry)

b = np.array(last_entries)

solution = BackwardSubstitution(A, b)

print("Solution to vectors x1, x2 & x3:")
print(solution)

A
[[ 1  2 -3  9]
 [ 2 -1 -1  0]
 [ 4 -1  1  4]] 

A1
[[  1.   2.  -3.   9.]
 [  0.  -5.   5. -18.]
 [  4.  -1.   1.   4.]] 

A2
[[  1.   2.  -3.   9.]
 [  0.  -5.   5. -18.]
 [  0.  -9.  13. -32.]] 

A3
[[  1.    2.   -3.    9. ]
 [ -0.    1.   -1.    3.6]
 [  0.   -9.   13.  -32. ]] 

A4
[[ 1.   2.  -3.   9. ]
 [-0.   1.  -1.   3.6]
 [ 0.   0.   4.   0.4]] 

Solution to vectors x1, x2 & x3:
[-4.550000000000001, 5.85, 2.25]


b. <br>
\begin{equation}
x+2y= -1 \\
2x+y+z = 1 \\
-x+y-z = -1
\end{equation}

Manual Solution:<br><br>
$
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    2 & 1 & 1 &\bigm| & 1 \\
    -1 & 1 & -1 &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & -3 & 1 &\bigm| & 3 \\
    -1 & 1 & -1 &\bigm| & -1 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{1}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & -3 & 1 &\bigm| & 3 \\
    0 & 3 & -1 &\bigm| & -2 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{pmatrix}
    1 & 2 & 0 &\bigm| & -1 \\
    0 & -3 & 1 &\bigm| & 3 \\
    0 & 0 & 0 &\bigm| & 1 \\
\end{pmatrix}
$

In [26]:
#Pythonic Solution#
A = np.array([[1, 2, 0, -1],
              [2, 1, 1, 1],
              [-1, 1, -1, -1]])

print("A")
print(A,'\n')
A = RowAdd(A, 0, 1, -2)
print("A1")
print(A,'\n')
A = RowAdd(A, 0, 2, 1)
print("A2")
print(A,'\n')
A = RowAdd(A, 1, 2, 1)
print("A3")
print(A,'\n')

last_entries = [] 
for row in A:
    last_entry = row[-1]
    last_entries.append(last_entry)

b = np.array(last_entries)

solution = BackwardSubstitution(A, b)

print("Solution to vectors x, y & z:")
print(solution)
print("Not possible since 0x + 0y + 0z != 1")

A
[[ 1  2  0 -1]
 [ 2  1  1  1]
 [-1  1 -1 -1]] 

A1
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [-1.  1. -1. -1.]] 

A2
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [ 0.  3. -1. -2.]] 

A3
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [ 0.  0.  0.  1.]] 

Solution to vectors x, y & z:
[3.0, -1.0, 0]
Not possible since 0x + 0y + 0z != 1


c. <br>
\begin{equation}
x_1-3x_2-2x_3=0 \\
-x_1+2x_2+x_3=0 \\
2x_1+4x_2+6x_3=0 \\
\end{equation}
<br>

Manual Solution:<br><br>
$
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    -1 & 2 & 1 &\bigm| & 0 \\
    2 & 4 & 6 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1 &\bigm| & 0 \\
    2 & 4 & 6 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} - 2\text{R}_{1}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1 &\bigm| & 0 \\
    0 & 10 & 10 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{3} + 10\text{R}_{2}}
\begin{pmatrix}
    1 & -3 & -2 &\bigm| & 0 \\
    0 & -1 & -1 &\bigm| & 0 \\
    0 & 0 & 0 &\bigm| & 0 \\
\end{pmatrix}
\xrightarrow{\text{R}_{1} - 3\text{R}_{2}}
\begin{pmatrix}
    1 & 0 & 1 &\bigm| & 0 \\
    0 & 1 & 1 &\bigm| & 0 \\
    0 & 0 & 0 &\bigm| & 0 \\
\end{pmatrix}
$
<br><br>
L3: 0x1 + 0x2 + 0x3 = 0, therefore x3 can have any value.<br>
L2: x2 + x3 = 0 = x2 = -x3<br>
L1: x1 + x3 = 0 = x1 + -x3<br>

In [25]:
#Pythonic Solution#
A = np.array([[1, -3, -2, 0],
              [-1, 2, 1, 0],
              [2, 4, 6, 0]])

print("A")
print(A,'\n')
A = RowAdd(A, 0, 1, 1)
print("A1")
print(A,'\n')
A = RowAdd(A, 0, 2, -2)
print("A2")
print(A,'\n')
A = RowAdd(A, 1, 2, 10)
print("A3")
print(A,'\n')
A = RowAdd(A, 1, 0, -3)
print("A4")
print(A,'\n')


last_entries = [] #to get the coefficient array for b

for row in A:
    last_entry = row[-1]
    last_entries.append(last_entry)

b = np.array(last_entries)

solution = BackwardSubstitution(A, b)

print("Solution to vectors x1, x2 & x3:")
print(solution)

A
[[ 1 -3 -2  0]
 [-1  2  1  0]
 [ 2  4  6  0]] 

A1
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 2.  4.  6.  0.]] 

A2
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 0. 10. 10.  0.]] 

A3
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 0.  0.  0.  0.]] 

A4
[[ 1.  0.  1.  0.]
 [ 0. -1. -1.  0.]
 [ 0.  0.  0.  0.]] 

Solution to vectors x1, x2 & x3:
[0.0, -0.0, 0]


d. <br>
\begin{equation}
w+x+2y+z=1 \\
w-x-y+z=0 \\
x+y=1 \\
w+x+z=2
\end{equation}
<br>

Manual Solution:<br><br>
$
\begin{align}
w + x + 2y + z &= 1 \\
w - x - y + z &= 0 \\
x + y &= 1 \\
w + x + z &= 2
\end{align}\\
$
<br><br>
$
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
1 & -1 & -1 & 1 & \big| & 0 \\
0 & 1 & 1 & 0 & \big| & 1 \\
1 & 1 & 0 & 1 & \big| & 2 \\
\end{bmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & -3 & 0 & \big| & -1 \\
0 & 1 & 1 & 0 & \big| & 1 \\
1 & 1 & 0 & 1 & \big| & 2 \\
\end{bmatrix}
\xrightarrow{\text{R}_{3} + 2\text{R}_{2}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & -3 & 0 & \big| & -1 \\
0 & 0 & 1 & 0 & \big| & 1 \\
1 & 1 & 0 & 1 & \big| & 2 \\
\end{bmatrix}
\xrightarrow{\text{R}_{4} + \text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & -3 & 0 & \big| & -1 \\
0 & 0 & 1 & 0 & \big| & 1 \\
1 & 1 & -1 & 1 & \big| & 3 \\
\end{bmatrix}
\xrightarrow{-1\text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & -3 & 0 & \big| & -1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & -1 & 1 & \big| & 3 \\
\end{bmatrix}
\xrightarrow{\text{R}_{2} - 2\text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 1 \\
0 & -2 & 1 & 0 & \big| & 1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & -1 & 1 & \big| & 3 \\
\end{bmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 2 \\
0 & -2 & 1 & 0 & \big| & 1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & -1 & 1 & \big| & 3 \\
\end{bmatrix}
\xrightarrow{\text{R}_{4} - \text{R}_{3}}
\begin{bmatrix}
1 & 1 & 2 & 1 & \big| & 2 \\
0 & -2 & 1 & 0 & \big| & 1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & 0 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{\text{R}_{1} - 2\text{R}_{3}}
\begin{bmatrix}
1 & 1 & 0 & 1 & \big| & 4 \\
0 & -2 & 1 & 0 & \big| & 1 \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & 0 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{-\frac{1}{2}\text{R}_{2}}
\begin{bmatrix}
1 & 1 & 0 & 1 & \big| & 4 \\
0 & 1 & -\frac{1}{2} & 0 & \big| & -\frac{1}{2} \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & 0 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{2}}
\begin{bmatrix}
1 & 0 & \frac{1}{2} & 1 & \big| & \frac{9}{2} \\
0 & 1 & -\frac{1}{2} & 0 & \big| & -\frac{1}{2} \\
0 & 0 & -1 & 0 & \big| & -1 \\
1 & 1 & 0 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{\text{R}_{4} - \text{R}_{1}}
\begin{bmatrix}
1 & 0 & \frac{1}{2} & 1 & \big| & \frac{9}{2} \\
0 & 1 & -\frac{1}{2} & 0 & \big| & -\frac{1}{2} \\
0 & 0 & -1 & 0 & \big| & -1 \\
0 & 0 & 1 & 1 & \big| & 4 \\
\end{bmatrix}
\xrightarrow{\text{R}_{1} - \text{R}_{4}}
\begin{bmatrix}
1 & 0 & 0 & 0 & \big| & 0 \\
0 & 1 & 0 & 0 & \big| & -\frac{1}{2} \\
0 & 0 & -1 & 0 & \big| & -1 \\
0 & 0 & 1 & 1 & \big| & 4 \\
\end{bmatrix}
$

\begin{align}
w &= 0 \\
x &= -\frac{1}{2} \\
y &= -1 \\
z &= 0 \\
\end{align}
<br>

In [8]:
#Pythonic Solution#
A = np.array([[1, 1, 2, 1, 1],
              [1, -1, -1, 1, 0],
              [0, 1, 1, 0, 1],
              [1, 1, 0, 1, 2]])

print("A")
print(A,'\n')
A = RowAdd(A, 0, 1, -1)
print("A1")
print(A,'\n')
A = RowAdd(A, 1, 2, 2)
print("A2")
print(A,'\n')
A = RowAdd(A, 2, 3, 1)
print("A3")
print(A,'\n')
A = RowScale(A, 2, -1)
print("A4")
print(A,'\n')
A = RowAdd(A, 2, 1, -2)
print("A5")
print(A,'\n')
A = RowAdd(A, 2, 0, -1)
print("A6")
print(A,'\n')
A = RowAdd(A, 2, 3, -1)
print("A7")
print(A,'\n')
A = RowAdd(A, 2, 0, -2)
print("A8")
print(A,'\n')
A = RowScale(A, 1, -1/2)
print("A9")
print(A,'\n')
A = RowAdd(A, 1, 0, -1)
print("A10")
print(A,'\n')
A = RowAdd(A, 0, 3, -1)
print("A11")
print(A,'\n')
A = RowAdd(A, 3, 0, -1)
print("A12")
print(A,'\n')

last_entries = [] 
for row in A:
    last_entry = row[-1]
    last_entries.append(last_entry)

b = np.array(last_entries)

solution = BackwardSubstitution(A, b)

print("Solution to vectors x, y, z, w:")
print(solution)

A
[[ 1  1  2  1  1]
 [ 1 -1 -1  1  0]
 [ 0  1  1  0  1]
 [ 1  1  0  1  2]] 

A1
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [ 0.  1.  1.  0.  1.]
 [ 1.  1.  0.  1.  2.]] 

A2
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [ 0. -3. -5.  0. -1.]
 [ 1.  1.  0.  1.  2.]] 

A3
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [ 0. -3. -5.  0. -1.]
 [ 1. -2. -5.  1.  1.]] 

A4
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [-0.  3.  5. -0.  1.]
 [ 1. -2. -5.  1.  1.]] 

A5
[[  1.   1.   2.   1.   1.]
 [  0.  -8. -13.   0.  -3.]
 [ -0.   3.   5.  -0.   1.]
 [  1.  -2.  -5.   1.   1.]] 

A6
[[  1.  -2.  -3.   1.   0.]
 [  0.  -8. -13.   0.  -3.]
 [ -0.   3.   5.  -0.   1.]
 [  1.  -2.  -5.   1.   1.]] 

A7
[[  1.  -2.  -3.   1.   0.]
 [  0.  -8. -13.   0.  -3.]
 [ -0.   3.   5.  -0.   1.]
 [  1.  -5. -10.   1.   0.]] 

A8
[[  1.  -8. -13.   1.  -2.]
 [  0.  -8. -13.   0.  -3.]
 [ -0.   3.   5.  -0.   1.]
 [  1.  -5. -10.   1.   0.]] 

A9
[[  1.   -8.  -13.    1.   -2. ]
 [ -0.    4.    6.5  -0

6. Determine if the vectors are linear combinations<br>
a. <br>
$
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} -1 \\ 3 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 2 \\ -6 \end{bmatrix}\\
\end{equation}
$
<br>
$
\begin{equation}
    \begin{bmatrix} 1 \\ 2 \end{bmatrix}x +
    \begin{bmatrix} -1 \\ 3 \end{bmatrix}y =
    \begin{bmatrix} 2 \\ -6 \end{bmatrix}
\end{equation}
$
<br>
<br>
$
\begin{equation}
    \begin{bmatrix}
        -1 & 2 & 1 \\
        3 & -6 & 2
    \end{bmatrix}
    \xrightarrow[]{\text{R}_{2} + 3\text{R}_{1}}
    \begin{bmatrix}
        -1 & 2 & 1 \\
        0 & 0 & 5
    \end{bmatrix}
\end{equation}
$
<br>
<br>**Not a linear combination**<br>

In [13]:
import numpy as np

v = np.array([1, 2])
u2 = np.array([-1, 3])
u3 = np.array([2, -6])

coeff_matrix = np.vstack((u2, u3)).T
constants = v

if np.linalg.matrix_rank(coeff_matrix) == np.linalg.matrix_rank(np.vstack((coeff_matrix, constants)).T):
    print("Is a linear combination.")
else:
    print("Not a linear combination.")

Not a linear combination.


b. <br>
$
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
$
<br>
$
 \begin{equation}
    \begin{bmatrix}
        1 & 0 | 1\\
        1 & 1 | 2\\
        0 & 1 | 3\\
    \end{bmatrix}
    \xrightarrow[]{R_2 - x + 2_y = -12_x + y + z = 1 - x + y - z = -1}
    \begin{bmatrix}
        1 & 0 | 1\\
        1 & 1 | 1\\
        0 & 1 | 3\\
    \end{bmatrix}
    \xrightarrow[]{R_3 - R_2}   
    \begin{bmatrix}
        1 & 0 | 1\\
        0 & 1 | 1\\
        0 & 0 | 2\\
    \end{bmatrix}
\end{equation}
$
<br>
<br>**Not a linear combination.**<br>

In [14]:
v = np.array([1, 2, 3])
u2 = np.array([1, 1, 0])
u3 = np.array([0, 1, 1])

coeff_matrix = np.vstack((u2, u3)).T
constants = v

if np.linalg.matrix_rank(coeff_matrix) == np.linalg.matrix_rank(np.column_stack((coeff_matrix, constants))):
    print("Is a linear combination.")
else:
    print("Not a linear combination.")

Not a linear combination.


c. <br>
$
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}
$
<br>
$
\begin{equation}
    \begin{bmatrix} 1 \\ 1 \\ 0\end{bmatrix}x +
    \begin{bmatrix} 0 \\ 1 \\ 1\end{bmatrix}y =
    \begin{bmatrix} 3 \\ 1 \\ -2\end{bmatrix}
\end{equation}
$
<br>
$
\begin{equation}
    \begin{bmatrix}
        1 & 0 & 3 \\
        1 & 1 & 1 \\
        0 & 1 & -2\\
    \end{bmatrix}
    x = 3,y = -2,x + y = 1x + y = 1 \xrightarrow[]{} 3 - 2 = 1
\end{equation}
$
<br>
$
\begin{equation}
    \begin{bmatrix} 3 \\ 3 \\ 0\end{bmatrix} +
    \begin{bmatrix} 0 \\ -2 \\ -2\end{bmatrix} =
    \begin{bmatrix} 3 \\ 1 \\ -2\end{bmatrix}
\end{equation}
$
<br>
<br>**Is a linear combination.**<br>

In [15]:
v = np.array([3, 1, -2])
u2 = np.array([0, -2, -2])
u3 = np.array([3, 1, -2])

coeff_matrix = np.vstack((u2, u3)).T
constants = v

if np.linalg.matrix_rank(coeff_matrix) == np.linalg.matrix_rank(np.column_stack((coeff_matrix, constants))):
    print("Is a linear combination.")
else:
    print("Not a linear combination.")

Is a linear combination.


<br>8. Show that the followwing vectors are linearly independent:
<br>a.
a. <br>
$
\begin{equation}
\begin{bmatrix} 3 \\ -1 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} -1 \\ 2 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 1 \\ 1 \\ 3 \\ 1 \end{bmatrix}
\begin{bmatrix} -1 \\ -1 \\ 1 \\ 3 \end{bmatrix}
\end{equation} 
$
<br>Transform it into reduced echelon form. <br><br>
$
    \begin{pmatrix}
    3 & -1 & 1 & -1 \\
    -1 & 2 & 1 & -1 \\
    1 & 1 & 3 & 1 \\
    -1 & -1 & 1 & 3\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{1} \leftrightarrow \text{R}_{3}}
    \begin{pmatrix}
    1 & 1 & 3 & 1 \\
    -1 & 2 & 1 & -1 \\
    3 & -1 & 1 & -1 \\
    -1 & -1 & 1 & 3\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{2} + \text{R}_{1}}
    \begin{pmatrix}
    1 & 1 & 3 & 1 \\
    0 & 3 & 4 & 0 \\
    3 & -1 & 1 & -1 \\
    -1 & -1 & 1 & 3\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{3} - 3\text{R}_{1}}
    \begin{pmatrix}
    1 & 1 & 3 & 1 \\
    0 & 3 & 4 & 0 \\
    0 & -4 & -8 & -4 \\
    -1 & -1 & 1 & 3\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{4} + \text{R}_{1}}
    \begin{pmatrix}
    1 & 1 & 3 & 1 \\
    0 & 3 & 4 & 0 \\
    0 & -4 & -8 & -4 \\
    0 & 0 & 4 & 4\\
    \end{pmatrix}
    $ <br><br> 
    $
    \xrightarrow[\frac{1}{4}\text{R}_{3}]{\frac{1}{4}\text{R}_{4}}
    \begin{pmatrix}
    1 & 1 & 3 & 1 \\
    0 & 3 & 4 & 0 \\
    0 & -1 & -2 & -1 \\
    0 & 0 & 1 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{1} + \text{R}_{3}}
    \begin{pmatrix}
    1 & 0 & 1 & 0 \\
    0 & 3 & 4 & 0 \\
    0 & -1 & -2 & -1 \\
    0 & 0 & 1 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{3} + \text{R}_{4}}
    \begin{pmatrix}
    1 & 0 & 1 & 0 \\
    0 & 3 & 4 & 0 \\
    0 & -1 & -1 & 0 \\
    0 & 0 & 1 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{2} + 3\text{R}_{3}}
    \begin{pmatrix}
    1 & 0 & 1 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & -1 & -1 & 0 \\
    0 & 0 & 1 & 1\\
    \end{pmatrix}
    \xrightarrow[-\text{R}_{3}]{\text{R}_{1} - \text{R}_{2}}
    \begin{pmatrix}
    1 & 0 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 1 & 1 & 0 \\
    0 & 0 & 1 & 1\\
    \end{pmatrix}
    \xrightarrow[\text{R}_{3} - \text{R}_{2}]{\text{R}_{4} - \text{R}_{2}}
    \begin{pmatrix}
    1 & 0 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 0 & 1\\
    \end{pmatrix}
$ <br><br>
Each column has a leading entry that is not zero and occurs higher than any non-zero entries in the same column and also there are no non-zero rows below the last pivot element which makes this **linearly dependent**.
<br><br>

b. <br>
$
\begin{equation}
\begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 0 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 4 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\end{equation}
$
<br><br>
Transform it into reduced row echelon form<br><br>
$
    \begin{pmatrix}
    0 & 0 & 0 & 4 \\
    0 & 0 & 3 & 3 \\
    0 & 2 & 2 & 2 \\
    1 & 1 & 1 & 1\\
    \end{pmatrix}
    \xrightarrow[\text{R}_{1} \leftrightarrow \text{R}_{4}]{\text{R}_{2} \leftrightarrow \text{R}_{3}}
    \begin{pmatrix}
    1 & 1 & 1 & 1 \\
    0 & 2 & 2 & 2 \\
    0 & 0 & 3 & 3 \\
    0 & 0 & 0 & 4 \\
    \end{pmatrix}
    \xrightarrow[\frac{1}{2}\text{R}_{2}]{\frac{1}{3}\text{R}_{3}}
    \begin{pmatrix}
    1 & 1 & 1 & 1 \\
    0 & 1 & 1 & 1 \\
    0 & 0 & 1 & 1 \\
    0 & 0 & 0 & 4 \\
    \end{pmatrix}
    \xrightarrow[\frac{1}{4}\text{R}_{4}]{\text{R}_{1} - \text{R}_{2}}
    \begin{pmatrix}
    1 & 0 & 0 & 0 \\
    0 & 1 & 1 & 1 \\
    0 & 0 & 1 & 1 \\
    0 & 0 & 0 & 1 \\
    \end{pmatrix}
    \xrightarrow[\text{R}_{2} - \text{R}_{3}]{\text{R}_{3} - \text{R}_{4}}
    \begin{pmatrix}
    1 & 0 & 0 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 0 & 0 & 1 \\
    \end{pmatrix}
    $<br><br>
    Since it is in its reduced row echelon form and satisfies the criteria to not be linearly dependent, therefore the vectors are **linearly independent**.<br>

c. <br>
$
\begin{equation}
\begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix}
\begin{bmatrix} -1 \\ 1 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 1 \\ 0 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 0 \\ 1 \\ -1 \\ 1 \end{bmatrix}
\end{equation}
$
<br><br>
Transform into reduced row echelon form.<br>
$
    \begin{pmatrix}
    1 & -1 & 1 & 0 \\
    -1 & 1 & 0 & 1 \\
    1 & 0 & 1 & -1 \\
    0 & 1 & -1 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{2} + \text{R}_{3}}
    \begin{pmatrix}
    1 & -1 & 1 & 0 \\
    0 & 1 & 1 & 0 \\
    1 & 0 & 1 & -1 \\
    0 & 1 & -1 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{3} + \text{R}_{4}}
    \begin{pmatrix}
    1 & -1 & 1 & 0 \\
    0 & 1 & 1 & 0 \\
    1 & 1 & 0 & 0 \\
    0 & 1 & -1 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{4} + \text{R}_{1}}
    \begin{pmatrix}
    1 & -1 & 1 & 0 \\
    0 & 1 & 1 & 0 \\
    1 & 1 & 0 & 0 \\
    1 & 0 & 0 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{3} - \text{R}_{1}}
    \begin{pmatrix}
    1 & -1 & 1 & 0 \\
    0 & 1 & 1 & 0 \\
    0 & 2 & -1 & 0 \\
    1 & 0 & 0 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{3} + \text{R}_{2}}
    $<br><br>
    $
    \begin{pmatrix}
    1 & -1 & 1 & 0 \\
    0 & 1 & 1 & 0 \\
    0 & 3 & 0 & 0 \\
    1 & 0 & 0 & 1\\
    \end{pmatrix}
    \xrightarrow{\frac{1}{3}\text{R}_{3}}
    \begin{pmatrix}
    1 & -1 & 1 & 0 \\
    0 & 1 & 1 & 0 \\
    0 & 1 & 0 & 0 \\
    1 & 0 & 0 & 1\\
    \end{pmatrix}
    \xrightarrow[\text{R}_{2} - \text{R}_{3}]{\text{R}_{1} + \text{R}_{3}}
    \begin{pmatrix}
    1 & 0 & 1 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 1 & 0 & 0 \\
    1 & 0 & 0 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{1} - \text{R}_{2}}
    \begin{pmatrix}
    1 & 0 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 1 & 0 & 0 \\
    1 & 0 & 0 & 1\\
    \end{pmatrix}
    \xrightarrow{\text{R}_{4} - \text{R}_{1}}
    \begin{pmatrix}
    1 & 0 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 0 & 1\\
    \end{pmatrix}
    $
 <br><br>
Since it is in its reduced row echelon form and satisfies the criteria to not be linearly dependent, therefore the vectors are **linearly independent**.